# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  compass: rupal/compass@0.0.26
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "test"
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "build"
  deploy:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "deployment" 
  notify:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "notify"
workflows:
  build-test-deploy-workflow:
    jobs:
      - build
      - test:
         requires:
          - build
      - deploy:
         requires:
           - test
         context: compass-integration-yoda100
         post-steps:
           - compass/notify_deployment
  build-deploy-workflow:
    jobs:
      - build
      - deploy:
         requires:
           - build
         context: compass-integration-yoda100
         post-steps:
           - compass/notify_deployment
  test-workflow:
    jobs:
      - build
      - deploy:
         requires:
           - build
      - notify:
         requires:
           - build
           